# Generated by Django 4.2.7 on 2025-10-15 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_apellido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='apellido',
        ),
    ]
